theme: minima
title: Something Science
author: Elizabeth Drueke
email: elizabethdrueke@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Need to come up with some interesting description of the page.

# social links
twitter_username: elizabethdrueke # DO NOT include the @ character, or else the build will fail!
github_username:  EDrueke1994 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
